### ISSUE TITLE
Error reading resource 0x6B20C4F3-0x00000000-0x591AE908972835D7

### ISSUE THREAD

**Issue by kactga** [Kuree/Sims4Tools#34]
![2558-01-14_2021](https://cloud.githubusercontent.com/assets/10531511/5739347/3e962490-9c2b-11e4-9baf-067b6cf16e18.png)
after I update the sims 4 today 
I can't open file Strings_ENG_US.package
or do anything it's show error like this 
what can I do please tell me 
I use s4pe v0.3b
Thanks in advance for your answer 
PS.I want to translate my the sims 4 to my language

**Comment by Kuree** [comment]
Hi, please use 7zip to unzip the file. Or just use the installer.

**Comment by kactga** [comment]
Thank you for your answer
Someone told me to use 7zip  , before you answer (Ha Ha)
that's why I closed this topic
but thank you very much for your answer really (I think you not answer topic has closed , but you do...make me impress :100: )
If I get problem for use it again I'll ask you 

Thank you very very much
