### ISSUE TITLE
Crash on export

### ISSUE THREAD

**Issue by KhArtNJava** [Kuree/Sims4Tools#36]
Hello.
I am trying to export DATA
System.InvalidOperationException: Could not find a resource handler
   в s4pi.WrapperDealer.WrapperDealer.WrapperForType(String type, Int32 APIversion, Stream s)
   в s4pi.WrapperDealer.WrapperDealer.GetResource(Int32 APIversion, IPackage pkg, IResourceIndexEntry rie, Boolean AlwaysDefault)
   в S4PIDemoFE.MainForm.exportFile(IResourceIndexEntry rie, String filename)
   в S4PIDemoFE.MainForm.resourceExport()
   в S4PIDemoFE.MainForm.menuBarWidget1_MBResource_Click(Object sender, MBClickEventArgs mn)
   в S4PIDemoFE.MenuBarWidget.OnMBResource_Click(Object sender, MB mn)
   в S4PIDemoFE.MenuBarWidget.tsCMSBW_Click(Object sender, EventArgs e)
   в System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
s4pe
    Версия сборки: 1409.20.48.34124
    Версия Win32: 1409.20.48.34124
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pe.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Custom
    Версия сборки: 1412.28.57.34110
    Версия Win32: 1412.28.57.34110
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/System.Custom.DLL
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
s4pi.CustomForms
    Версия сборки: 1412.28.57.34110
    Версия Win32: 1412.28.57.34110
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pi.CustomForms.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
s4pi.Interfaces
    Версия сборки: 1412.28.57.34110
    Версия Win32: 1412.28.57.34110
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pi.Interfaces.DLL
----------------------------------------
s4pi.WrapperDealer
    Версия сборки: 1412.28.57.34111
    Версия Win32: 1412.28.57.34111
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pi.WrapperDealer.DLL
----------------------------------------
s4pi.Helpers
    Версия сборки: 1412.28.57.34112
    Версия Win32: 1412.28.57.34112
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pi.Helpers.DLL
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
s4pi.Package
    Версия сборки: 1412.28.57.34111
    Версия Win32: 1412.28.57.34111
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pi.Package.DLL
----------------------------------------
s4pi.Settings
    Версия сборки: 1412.28.57.34110
    Версия Win32: 1412.28.57.34110
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pi.Settings.DLL
----------------------------------------
s4pi.Extensions
    Версия сборки: 1412.28.57.34111
    Версия Win32: 1412.28.57.34111
    CodeBase: file:///C:/Art/Projects/sims3tools/s4pe.0.3.b/s4pi.Extensions.DLL
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by IngeJones** [comment]
Any error that says "could not find a resource handler" means you didn't unzip the tool right in the first place.  Didn't you use the self-installing download version?

**Comment by KhArtNJava** [comment]
No, I have downloaded zip. What is correct "the first place"? I've downloaded zip, unpacked with WinRAR...

**Comment by KhArtNJava** [comment]
Solved with exe installer...

**Comment by Kuree** [comment]
I use 7z to pack all the files. As far as I know using winrar will cause some problems here.
