### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by KhArtNJava** [Kuree/Sims4Tools#38]
In last issue https://github.com/Kuree/Sims4Tools/issues/37 I have used incorrect data for example.
I used for Instance field data, generated with FNV64 Button - it's incorrect for adding _XML 0xE882D22F interaction object. 
In official docs has info 
Packaging
The instance IDs for tuning should be generated using the following process:
Step Result
Resource Name Buff_Trait_Novelist
Your Name SimGuruModSquad
Combine Them SimGuruModSquad:Buff_Trait_Novelist
Convert to Lower Case simgurumodsquad:buff_trait_novelist
64-bit FNV-1 Hash 0x48a4d404a5a3bb0e
Set High Bit (‘OR’ with 0x8000000000000000) 0xc8a4d404a5a3bb0e

Can you realize option in s4pe - button or checkbox - for operation "Set High Bit (‘OR’ with 0x8000000000000000)"? It must generate 64-bit FNV-1 Hash from Name field and after that must set high bit for generated value.

Thank you.

**Comment by Kuree** [comment]
For the last issue I disabled the namemap resource because it is not used in EA's package. I forgot that s4pe's UI still relies on the namemap resource. 

I agree with you on this feature and I will add a button in the Hash panel to set the high bit. All the new features and bug fixes will be shipped with next version.

**Comment by KhArtNJava** [comment]
OK.
When you will have changes in the code on this issue, please, write here - I will compile s4pe from sources - I don't want new release...

**Comment by Kuree** [comment]
All the codes here are updated. I only make public release when there're significant amount of commits.

**Comment by KhArtNJava** [comment]
I say about future commit with this enhancement... Sorry my bad English :)

**Comment by Kuree** [comment]
Added in d1278780c925f6062b4d232c1e3db9966f749c81.

**Comment by KhArtNJava** [comment]
Works good. Thank you.
