### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by focusedgirl** [Kuree/Sims4Tools#40]
Does S4PE have a command line interface?  I would like to be able to automate my package tasks with batch scripts, but I have yet to find anything for Sims 4 that has a command line interface.  Is there anything that you can do for me?

**Comment by Kuree** [comment]
Yes, I can. But can you specify more details about what type of functionality you want? If it simply displays all the TGI, then the screen will blow up for large package files.

**Comment by focusedgirl** [comment]
I noticed that the _DDS resources that have the shuffled option compress better, but many of the packages in my mods folder don't use that option.  I would like to be able to shuffle all of them with a command line option instead of having to open each package one by one and click Texture Shuffled on each dds.

**Comment by Kuree** [comment]
Oh I see. You're asking a feature for the helper. Please repost your feature request there: https://github.com/Kuree/s4p4-helper. 

I'm going to close this issue as it's irrelevant here.
