### ISSUE TITLE
S4PE after save file

### ISSUE THREAD

**Issue by ishlimitx** [Kuree/Sims4Tools#67]
i downloaded S4PE to unmerge one of my merge file to take a cc of i didn't won't after i done so and did everything i save it and put my merge cc back into my mod's folder i went to my sims 4 to play it wouldn't load at all so i went to go back to my mod's folder and see if maybe if i take that out it might work and it did my the thing is all my cc i have on there is not on my sims because if i put it back in my mod's folder my game one load is that a way i can fix this.

**Comment by Kuree** [comment]
Hello,

Sorry about your situation. However, this repo is deprecated and I don't think S4PE will help you that much. You can try to create an issue at https://github.com/s4ptacle/Sims4Tools or at modthesims.info
